### ISSUE TITLE
Problem with enter url https://mysite.com/f/akhs

### ISSUE THREAD

**Issue by raymand211092** [8Mi-Tech/yourls-conditional-urlads#3]
Warning: Undefined variable $TRIGGERS in /media/drive/www/public/shortlink/user/plugins/yourls-conditional-urlads/plugin.php on line 19

**Comment by raymand211092** [comment]
Solved change php version for 7.4

**Comment by 8MiYile** [comment]
@raymand211092 Oh sorry, I forgot to provide the minimum PHP version!
